export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ID_REPOSITORY = 'ID_REPOSITORY';
export const ID_REDIS_NAMESPACE = 'ID_REDIS_NAMESPACE';
export const OUTSIDE_REPOSITORY = 'OUTSIDE_REPOSITORY';
